---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Replication and Reproducibility in Social Sciences and Statistics: Context, Concerns, and Concrete Measures"'
categories: 'Lecture'

# Event categories
event:
  title: '"Replication and Reproducibility in Social Sciences and Statistics: Context, Concerns, and Concrete Measures"'
  description: ""
  categories:  'Lecture'
  date: "April 02, 2019"
  end_date: "April 02, 2019"
  time: "10:30–12:00"
  location:
    name: "Ludwigstr. 28,Room 221"
    address: ""
    map_url: ""
  format:
    type: 'Lecture'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>We are glad to announce the following upcoming talk "<strong>Replication and Reproducibility in Social Sciences and Statistics: Context, Concerns, and Concrete Measures</strong>" by <strong>Dr. Lars Vilhuber</strong> who is Executive Director of the <a href="https://www.ilr.cornell.edu/labor-dynamics-institute">Labor Dynamics Institute at Cornell University</a> &amp; <a href="https://www.aeaweb.org/">AEA</a> Data Editor (<a href="https://www.vilhuber.com/lars/">https://www.vilhuber.com/lars</a>)</p><p><strong>Abstract:</strong><br>Data and the statistical program codes to analyze them are an elementary part of any empirical analysis in all fields of science. Nevertheless, especially in the social sciences this “data work” is most often not directly subject to the scientific quality control, namely the review process of scholarly articles before publication. (How) Has this contributed to the so-called "replication crisis", i.e. the fact that a lot of scientific findings cannot be reproduced? But what is replication and reproducibility? Is it really a crisis and if yes, how bad is it? How can the situation be improved and who can do it? These and many other questions will be addressed by Lars Vilhuber (<a href="https://www.vilhuber.com/lars/">https://www.vilhuber.com/lars</a>) in his (English) presentation, which is organized by the Collaborative Research Center Transregio “Rationality and Competition” (<a href="https://rationality-and-competition.de/">https://rationality-and-competition.de/</a>) and the LMU-ifo Economics &amp; Business Data Center (<a href="https://www.cesifo-group.de/de/ifoHome/facts/EBDC.html">https://www.cesifo-group.de/de/ifoHome/facts/EBDC.html</a>) in collaboration with the LMU Open Science Center (<a href="https://www.osc.uni-muenchen.de/index.html">https://www.osc.uni-muenchen.de/</a>) and the LMU Center for Advanced Studies research focus “Evidence Based Practice” (<a href="https://www.cas.lmu.de/en/programs/cas-research-focuses/index.html">https://www.en.cas.uni-muenchen.de/research_focus/evidence_praxis/index.html</a>).</p><p><strong>Speaker</strong>:<br>Dr. Lars Vilhuber is Executive Director of the <a href="https://www.ilr.cornell.edu/labor-dynamics-institute">Labor Dynamics Institute at Cornell<br>University</a> and the <a href="https://www.aeaweb.org/">American Economic Association</a>’s Data Editor. In addition to labor economics, he has done extensive research on data publication/access despite privacy and confidentiality issues.</p><p><strong>Material:</strong></p><ul>
<li>Presentation: <a href="http://doi.org/10.5281/zenodo.3245369">http://doi.org/10.5281/zenodo.3245369</a>
</li>
<li>Replication Tutorial: <a href="https://labordynamicsinstitute.github.io/replication-tutorial-2019/#/">https://labordynamicsinstitute.github.io/replication-tutorial-2019/#/</a>
</li>
<li>Reproducibility Workshop: <a href="https://labordynamicsinstitute.github.io/computing4economists/web/#/">https://labordynamicsinstitute.github.io/computing4economists/web/#/</a><strong><br></strong>
</li>
</ul>
<p><strong>Registration</strong>:<br>As places are limited, we kindly ask for registration by email to <a class="g-link-mail" href="mailto:ebdc@ifo.de" title="Send email to: ebdc@ifo.de">ebdc@ifo.de</a> by Monday, June, 10.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
