---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Open Access: Options, Requirements and Funding Possibilities"'
categories: 'Workshop'

# Event categories
event:
  title: '"Open Access: Options, Requirements and Funding Possibilities"'
  description: ""
  categories:  'Workshop'
  date: "January 20, 2020"
  end_date: "January 20, 2020"
  time: "9:00"
  location:
    name: "Leopoldstr. 30, Training room S1, ground floor"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>We are offering a workshop on Open Access addressing LMU researches from all disciplines and of all career levels above PhD on 20 January 2020. The workshop aims at providing orientation on Open Access publications in general, on the available options before, during and after a research project as well as on specific requirements and funding possibilities by different funders.</p><p>The LMU Munich Open Science Center, the University Library and the Unit for Research Funding join forces to present you an overview on Open Access in order to enhance transparency and provide you with the necessary tools to fulfil the guidelines of research funders such as DFG and European Commission.</p><p>The workshop consists of information and discussion sessions and invites attendees to participate actively. Please spread this information to other interested LMU researchers. The number of participants is limited, slots will be available on a first come, first serve basis</p><p> </p><p>Trainer:</p><ul style="list-style-type: square;">
<li>PD Dr. Felix Schönbrodt, <a href="../../home_boxes/index.html" title="Welcome to the Open Science Center">LMU Open Science Center (OSC)</a>
</li>
<li>Volker Schallehn, Andrea Dorner, Vanessa Gabriel, <a href="https://www.en.ub.uni-muenchen.de/homepage/index.html" title="The University Library's most popular services at a glance:">LMU University Library</a>
</li>
<li>Dr. Veit Schwab, Dr. Anna Pahl, <a href="https://www.lmu.de/en/research/research-services/index.html">LMU Unit for Research Funding</a>
</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
