---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Discussion of central issues and papers concerning Open Science and related topics"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Discussion of central issues and papers concerning Open Science and related topics"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "January 29, 2020"
  end_date: "January 29, 2020"
  time: "12:30–14:00"
  location:
    name: "Leopoldstr. 13, Room 1407"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The interdisciplinary journal club “ReproJucibiliTea” will be launched every 3-4 weeks and address main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the name "ReproducibiliTea". The slogan of the new Journal-Club at LMU Munich is "ReproJuicebiliTea" matching the covered topics (Reproducibility &amp; Open Science) and the extended selection of drinks. Tea, juice and small snacks are provided to live up to the slogan. Everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p><br>On December 18th, 2019, the first session of the ReproJucibiliTea took place at Leopoldstrasse 13. Around 15 participants from different scientific fields (e.g. psychology, statistics, political sciences) including students, doctoral candidates and professors met to discuss the following chosen paper as a typical introduction to problems of credibility in science:</p><p><br>Ioannidis, J. P. A. (2005). Why Most Published Research Findings Are<br>False. PLoS Medicine, 2(8), 6. <a href="https://doi.org/10.1371/journal.pmed.0020124">https://doi.org/10.1371/journal.pmed.0020124</a></p><p> </p><p>In the second session solutions to improve the reproducibility and robustness of research will be discussed in the context of an introductory paper to Open Science.</p><ul style="list-style-type: square;">
<li>When? Wednesday, 29.01. 12.30-14 s.t.</li>
</ul>
<ul style="list-style-type: square;">
<li>Where? Leopoldstraße 13, room 1407 (Building 1, 4th floor)</li>
</ul>
<ul style="list-style-type: square;">
<li>Paper: Munafò, M. R., Nosek, B. A., Bishop, D. V. M., Button, K. S., Chambers, C. D., Percie du Sert, N., Simonsohn, U., Wagenmakers, E.-J., Ware, J. J., &amp; Ioannidis, J. P. A. (2017). A manifesto for reproducible science. Nature Human Behaviour, 1(1). <a href="https://doi.org/10.1038/s41562-016-0021">https://doi.org/10.1038/s41562-016-0021</a>
</li>
</ul>
<p>Again, we will start with a short summary of the paper and then continue with the discussion in which you can contribute your own thoughts and questions. Participants can use the following key questions to prepare for the discussion<strong>:</strong></p><ul style="list-style-type: square;">
<li>How can the system be changed in the long term, so that reproducible research is promoted independently of the research results?</li>
<li>How can we promote continuous education among scientists of all ages?</li>
<li>What changes are central to the training of young scientists in order promote sustainably robust and reproducible research?</li>
<li>What other problems could arise during and through the implementatio of the measures described in the article?</li>
</ul>
<p><br>If you are interested, you are cordially welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:stephan.nuding@yahoo.de" title="Send email to: stephan.nuding@yahoo.de">stephan.nuding@yahoo.de</a> to join the mailing list to get information about the next meetings and chosen papers.</p><p><br>For each session it would be helpful to have read the announced paper (but there will always a short summary to bring everyone on the same page). Then there is a discussion about the paper and related topics, in which you are able to bring in your own comments, questions or criticism.</p><p>Organizational team:</p><ul style="list-style-type: square;">
<li>PD Dr. Felix Schönbrodt, <a href="../../home_boxes/index.html" title="Welcome to the Open Science Center">LMU Open Science Center (OSC)</a>
</li>
<li>Laura Goetz, <a href="http://www.psy.lmu.de/fachpsy/index.html">students council of Psychology</a>
</li>
<li>Stephan Nuding, <a href="http://www.psy.lmu.de/fachpsy/index.html">students council of Psychology</a>
</li>
<li>Leonhard Schramm, <a href="http://www.psy.lmu.de/fachpsy/index.html">students council of Psychology</a>
</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
