---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Corona & Open Science: "Fieberhafte Forschung – Warum Forschung derzeit wenig verlässlich ist und was wir dagegen tun können"'
categories: 'Symposium'

# Event categories
event:
  title: '"Corona & Open Science: "Fieberhafte Forschung – Warum Forschung derzeit wenig verlässlich ist und was wir dagegen tun können"'
  description: ""
  categories:  'Symposium'
  date: "May 14, 2020"
  end_date: "May 14, 2020"
  time: "16:00–17:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Symposium'
    detail: ""
  language:
    primary: "German"
    primary-code: "de"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Am 14.05.2020 fand um 16 Uhr der erste Vortrag des OSC-Kolloquiums zu Corona &amp; Open Science als Online-Veranstaltung auf Zoom statt. Prof. Katrin Auspurg hielt dabei einen Vortrag mit dem Thema "Fieberhafte Forschung –Warum Forschung derzeit wenig verlässlich ist und was wir dagegen tun können".</p><p>Speaker:</p><p><a href="../../members/individual_members/lmu-members/auspurg/index.html" title="Auspurg">Prof. Katrin Auspurg</a></p><p>Abstract:</p><p>Derzeit gibt es aufgrund der Aussetzung üblicher Qualitätsstandards etliche Anzeichen für eine ineffiziente Wissenschaft. So werden Preprints oft ohne Begutachtungsverfahren zur Kenntnis genommen oder mit stark beschleunigten Verfahren in Journals publiziert. Offene Publikationen erhöhen zwar die Quantität der vorliegenden Forschung; ohne Qualitätsstandards und Kontrollen sind sie aber womöglich zu stark verzerrt, um hinreichend verlässliche Ergebnisse zu liefern. Der Beitrag illustriert das mit Beispielen aus der Medizin und insbesondere den Sozialwissenschaften, wie etwa arg „freihändig“ formulierten Thesen oder ad-hoc Surveys. Damit sich verlässliche wieder gegenüber überhasteter Forschung durchsetzen kann, scheinen Änderungen der Anreizstrukturen erforderlich. Die zentrale zu diskutierende These lautet hier: Open Science hilft durch offene Daten und transparente Materialien. Lediglich Open Access zu nicht oder rasch begutachteten Publikationen ist dagegen kein effizientes Mittel für einen effizienten Erkenntnisfortschritt, eher im Gegenteil.</p><p>Folien:</p><p><a href="osc-input-auspurg-2020-05-14.pdf" title="OSC_Input Auspurg_2020-05-14">Foliensatz_Fieberhafte Forschung_OSC-Kolloquium</a></p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
