---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Research Data Management & Open Science: Trends, Funding Requirements and Services at LMU"'
categories: 'Workshop'

# Event categories
event:
  title: '"Research Data Management & Open Science: Trends, Funding Requirements and Services at LMU"'
  description: ""
  categories:  'Workshop'
  date: "April 22, 2021"
  end_date: "April 22, 2021"
  time: "15:00-16:30"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The LMU Open Science Center, the Unit for Research Funding and the University Library cordially invite to the online workshop "Research Data Management &amp; Open Science: Trends, Funding Requirements and Services at LMU".</p><p>Research data management is becoming increasingly relevant across different scientific disciplines and fields. While more and more researchers actively choose to make their research data open, dedicated strategies for data management are required by funding agencies such as the European Commission, the DFG and BMBF. In the EU's new framework program Horizon Europe, Open Science is mandatory for all projects.<br>In this interactive workshop, the LMU Open Science Center, the Unit for Research Funding and the University Library join forces to present an overview on recent trends, funding requirements and services available at LMU. The workshop will be kicked off with a primer on the current discussions surrounding open data by Felix Schönbrodt, followed by a presentation by the Research Funding Unit on the policies of funders such as the German Research Foundation (DFG), BMBF and the European Commission, with a special focus on presenting data management and open data in the application. It will close with a hands-on presentation of online resources and tools that support researchers from creating data management plans to implementing effective data management workflows for their projects, including possible storage and open access strategies by the LMU University Library.</p><p>PS: After the workshop, the biannual members' meeting of the LMU Open Science Center will take place (from 5pm to 6pm). Participants of the workshop who are interested in the work of the OSC are cordially invited to join the members meeting as guests.</p><p>Speakers:</p><ul style="list-style-type: square;">
<li>Prof. Dr. Felix Schönbrodt, <a href="../../home_boxes/index.html" title="Welcome to the Open Science Center">LMU Open Science Center (OSC)</a>
</li>
<li>Dr. Florian Schneck &amp; Dr. Veit Schwab, <a href="https://www.lmu.de/en/research/research-services/index.html">LMU Unit for Research Funding</a>
</li>
<li>Laura Meier, Dr. Martin Spenger, <a href="https://www.en.ub.uni-muenchen.de/homepage/index.html" title="The University Library's most popular services at a glance:">LMU University Library</a>
</li>
</ul>
<div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
