---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Philosophy and Methodology of Medicine"'
categories: 'Lecture'

# Event categories
event:
  title: '"Philosophy and Methodology of Medicine"'
  description: ""
  categories:  'Lecture'
  date: "June 01, 2021"
  end_date: "June 01, 2021"
  time: "9:40-03.06.2021"
  location:
    name: "Online"
    address: ""
    map_url: ""
  format:
    type: 'Lecture'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>We are incredibly excited to announce an interesting online conference by the <a>Munich Center for Mathematical Philosophy (MCMP)</a>:</p><p> </p><p style="text-align: center;"><strong>"Philosophy and Methodology of Medicine"</strong></p><h3 style="text-align: left;"><strong>Idea &amp; Motivation</strong></h3><p>The claims of medicine have been supported by a wide variety of different methods, ranging from randomized controlled trials to expert judgement and mechanism-based reasoning. Miriam Solomon has therefore aptly characterized medicine in terms of a developing, untidy, methodological pluralism. But can philosophers help with this development? In recent years, philosophers of science have become increasingly interested in assessing the strengths and weaknesses of the various methods employed in medicine. Some have defended the methodological superiority of randomized controlled trials, or at least meta-analyses of such trials. Others have challenged this superiority by on the one hand stressing the weaknesses of such methods in terms of their internal or external validity, and on the other hand emphasising the strengths of alternative methods, including methods involving expert judgement and mechanistic evidence.</p><p>The online conference will bring together philosophers of science and medical methodologists in an attempt to make progress towards resolving these debates concerning the strengths and weaknesses of the various methods employed in medicine. Among others, the following topics will be covered within the conference:</p><ul>
<li>Foundational issues in statistics in medicine</li>
<li>Bias in medical inference</li>
<li>Medical epistemology</li>
<li>Multi-agent medical epistemology</li>
<li>Mechanisms in medicine</li>
<li>Analogy and extrapolation in medicine</li>
<li>Expert judgement in medicine</li>
</ul>
<p>The conference is organized by Dr. Jürgen Landes, a Postdoctoral Research Fellow at the <a>Munich Center for Mathematical Philosophy</a> and member of the <a href="../../index.html" title="eOpen Science Center">LMU Open Science Center (OSC)</a>, and <a href="https://www.kent.ac.uk/european-culture-languages/people/1679/wilde-michael">Dr. Michael Wild</a>, Admissions Officer for the <a href="https://www.kent.ac.uk/philosophy">Department of Philosophy at the University of Kent</a>.</p><p>More information about the schedule, all speakers and the presented topics can be found at the website of the conference.</p><p>If you are interested in participating, please send an email to juergen.landes@lrz.uni-muenchen.de with the following subject line: "Registration: Philosophy and Methodology of Medicine". A registration covers all three days. Registered participants are not required to attend all talks. </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
