---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Introducing mechanisms of robustness and transparency into the institutional incentive and reward system (MERIT)"'
categories: 'Workshop'

# Event categories
event:
  title: '"Introducing mechanisms of robustness and transparency into the institutional incentive and reward system (MERIT)"'
  description: ""
  categories:  'Workshop'
  date: "July 08, 2021"
  end_date: "July 08, 2021"
  time: "16:00-17:30"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The event will be opened by a keynote from Dr. Miriam Kip (<a href="https://www.bihealth.org/de/translation/innovationstreiber/quest-center/teams/quest-office">BIH/QUEST Berlin</a>) speaking about "Introducing mechanisms of robustness and transparency into the institutional incentive and reward system (MERIT)". Afterwards, the speaker will lead a workshop discussing how performance-based funding and appointment practices can be restructured and designed to reward good scientific practice.</p><h3>Abstract:</h3><p>In this workshop we will discuss relevant phases of the implementation process of open science as a new criterion in the institutional research assessment. Based on the experiences at Charité and BIH, we will elaborate in small groups (breakout rooms) on the following aspects of an implementation strategy: field and need assessment, stakeholder engagement, design of a new incentive, capacity building. The topics will be discussed with reference to the institutional environment at LMU.</p><p> </p><p>After the workshop, we kindly invite all members to the General Assembly of the LMU Open Science Center, including all representatives from our institutional members.</p><p>Since 2018, the center aims at fostering the engagement for open, transparent, and reproducible research. This goal is supported by research on research, training of researchers, and addressing relevant committees in order to create new and innovative incentive structures for open science. We are always looking for new members. If you are interested, please take a look at our <a>admission requirements</a> for more information.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
