---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Loss-of-Confidence Project - Have you ever lost faith in your scientific work?"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Loss-of-Confidence Project - Have you ever lost faith in your scientific work?"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "September 29, 2021"
  end_date: "September 29, 2021"
  time: "16:30-18:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>After a short summer break, the Journal Club: “ReproJuicebiliTea” at LMU Munich continues with its fourth meeting to discuss an interesting paper about mistakes and lost confidence in scientific work as well as how to deal with it. The organisation team is happy to announce that the paper’s author, Dr. Julia M. Rohrer, will give an introductory talk to this session and participate in the open discussion afterwards:</p><p>Participants can use the following <strong>key questions</strong> to prepare for the discussion:</p><ul>
<li>Which aspects are already relevant for students and should be taught? How should e.g. lost confidence in empirical work be dealt with in the course of the bachelor studies? What would you say about your own undergraduate empirical work today?</li>
<li>What mechanisms and practical handling of discoveries of errors or lost confidence in previous research would be desirable? Or are the structures already in place and just not being used sufficiently? If so, why not?</li>
<li>What are individuals missing in order to talk more openly about lost trust in their own work? And when does an open exchange about it take place instead?</li>
</ul>
<p><br>You can find a short abstract for the introductory talk by Dr. Julia M. Rohrer (University of Leipzig) below:</p><h3>Loss-of-Confidence Project – Have you ever lost faith in your scientific work?</h3><p>Mistakes are a routine part of the scientific process, and yet we rarely talk about them openly. Imagine you published a paper only to realize that the central conclusion was wrong because of a mistake you made. How would you deal with that? And, if you spoke about it openly, how would the scientific community react?</p><p>In this talk, Dr. Julia M. Rohrer will talk about the Loss-of-Confidence Project in which a group of psychological researchers publicly owned their mistakes. You will hear from researchers who made a mess and made amends as well as learn more about why retractions should become normalized.</p><p><strong>About the speaker</strong></p><p>Dr. Julia M. Rohrer is a personality psychologist by training and her work covers a broad range of topics, including the effects of birth order, age patterns in personality, and the correlates and determinants of subjective well-being. Her methodological interests include causal inference on the basis of observational data and data analytic flexibility. She is an active advocate for increased research transparency and has frequently given talks on the topic. Julia recently finished her doctoral degree as a fellow of the International Max Planck Research School on the Life Course and is now a lecturer (Akademische Assistentin) at the Department of Psychology, University of Leipzig.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproJucibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the name "ReproducibiliTea". The slogan of the Journal-Club at LMU Munich is "ReproJuicebiliTea" matching the covered topics (Reproducibility &amp; Open Science) and the extended selection of drinks. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, the meetings are hold online until it is possible to do them on site. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
