---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Getting active - How can we foster Open Science within our university?"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Getting active - How can we foster Open Science within our university?"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "July 08, 2022"
  end_date: "July 08, 2022"
  time: "14:30–16:00"
  location:
    name: "Hybrid (Room 3322 at Leopoldstraße 13, Munich or via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its seventh meeting to discuss how we can foster Open Science within our university. The organisation team is happy to announce that Dr. Malika Ihle (LMU Munich) will start with an introduction to the topic (roughly 20-30min). We will then continue with an open discussion in which you can contribute your own thoughts and questions.</p><p>The session including the open discussion afterwards will focus on general and concrete ideas on how to promote Open Science at a local level. Instead of recommending a paper as the basis for our discussion, we would simply ask you to think about some ideas to the following <strong>key questions</strong>:</p><ul>
<li>What are the most effective measures to enforce open science practices in your field?</li>
<li>What role do local Open Science initiatives (e.g. journal clubs) play in promoting Open Science?</li>
<li>What opportunities do you personally have to promote Open Science, and which might be most promising?</li>
</ul>
<p>Below, you can find a short abstract for the introductory presentation by Dr. Malika Ihle (LMU Open Science Center):</p><h3><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">Getting active – How can we foster Open Science within our university?</span></h3><p>The Open Science movement was very successful in recent years and has found more and more supporters. However, there is still a lot to be done to achieve the desired goal of transparent research process becoming the norm in science. But what would be the next steps and the most efficient measures to accelerate this cultural change towards Open Science? And how can each individual contribute to achieving this goal?</p><p>In this presentation, Dr. Malika Ihle will introduce a framework for fostering Open Science within the scientific community. She will discuss the different roles of bottom-up and top-down actions in the cultural change towards openness and transparency in science. Finally, she will talk about some specific ideas on how Open Science can be promoted at local level and what steps each individual could start with to growth their community.</p><p><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">About the speaker:</span></p><p>Dr. Malika Ihle is the Scientific Coordinator of the LMU Open Science Center and supports its scientific board to promote and foster Open Research across all disciplines within the LMU and beyond. Before she joined the LMU, she worked for 2.5 years in a similar position at the University of Oxford where she coordinated Reproducible Research Oxford (RROx). Malika is an Open Science enthusiast and expert, always looking for new ideas to advance the Open Science movement. Her experience ranges from providing Open Science training to coordinating grassroots-initiatives and co-developing strategic plans for universities to roll out Open Science practices across faculties and departments. She holds an PhD in Biology and is a founding member of the Society for Open, Reliable, and Transparent Ecology and Evolutionary biology (SORTEE).</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
