---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Elaborating the umbrella term: What is your idea of Open Science?"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Elaborating the umbrella term: What is your idea of Open Science?"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "November 25, 2022"
  end_date: "November 25, 2022"
  time: "14:30–16:00"
  location:
    name: "Hybrid (Room 3322 at Leopoldstraße 13, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its eleventh meeting, the second one for this semester. It will already take place this Friday and its purpose is to share, discuss and develop ideas about what the broad term and concept of open science is actually about and how it is intervened with other issues and concepts (e.g., research integrity, transparency, rigour of methods). For this session, it would be particularly helpful if people with different perspectives (e.g. disciplines, career stages) participated in order to get as diverse a picture of Open Science as possible.</p><p><strong>Paper:</strong> There is no specific paper that you should read for this session. Just bring in your own thoughts and ideas.</p><p><strong>Procedure:</strong>  Members of our organising team will give a short introduction at the beginning to introduce the topic and structure of this session. Then we will continue with group work in smaller groups. Finally, there will be enough time to collect all the ideas from the small groups and discuss them among all participants.</p><p>Below, you can find a short abstract for the session.</p><h3>Elaborating the umbrella term: What is your idea of Open Science?</h3><p>The umbrella term "Open Science" covers a wide range of different efforts that presumably have some central aspects in common. But what are these central aspects that are shared by all or most Open Science enthusiasts or researchers in general? And what other issues and concepts might be described as intertwined with or closely related to Open Science (e.g., research integrity, rigour of methods, inclusiveness, incentive structure)? In this session, we would like participants to share their different ideas and thoughts on what Open Science actually is, e.g. what its core values are, or on the other hand, what issues might still represent controversies within the Open Science movement. The aim is also to explore where one's own idea of Open Science is perhaps too narrow and where it could perhaps even be expanded. We hope that the contributions from different perspectives (e.g. scientific disciplines, qualitative/quantitative research) will help to broaden and sharpen the view of Open Science.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, PhD Student at the Chair of Social Psychology</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
<li>Franka Etzel, Psychology Student at LMU Munich</li>
<li>Viktoria Wiegelmann, Psychology Student at LMU Munich</li>
<li>Gracia Prüm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
