---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '" Open Science knowledge and prevalence of QRPs among students - a call to update our curricula"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '" Open Science knowledge and prevalence of QRPs among students - a call to update our curricula"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "July 22, 2022"
  end_date: "July 22, 2022"
  time: "14:30–16:00"
  location:
    name: "Hybrid (Room 3322 at Leopoldstraße 13, Munich or via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its eighth meeting to discuss Open Science knowledge and prevalence of QRPs among students. The organisation team is happy to announce that one of the paper’s and the position paper's authors, Maximilian Frank, will give an introductory talk to this session and participate in the open discussion afterwards:</p><p>Participants can use the following <strong>key questions</strong> to prepare for the discussion:</p><ul>
<li>How prevalent are the different QRPs among students and what are the reasons for these prevalence rates?</li>
<li>What further changes are needed in the curricula (of your discipline) in order to meet the demands for transparency and/or address the problems related to the replication crisis (in social sciences) adequately in the education of students?</li>
<li>What is the best way to implement changes in curricula on a broad scale? What can and should be done at local level and what role do structural/political changes play?</li>
</ul>
<p>You can find a short abstract for the introductory talk by Maximilian Frank below:</p><h3><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">Open Science knowledge and prevalence of QRPs among students - a call to update our curricula</span></h3><p>In recent years, there has been an intensive debate within psychology about the conclusions that should be drawn from the replication crisis. The use of questionable research practices (QRPs) was identified as one reason for problems concerning replicability. While there are extensive studies on the prevalence of QRPs among scientists, little is known about their occurrence among students. In his introduction, Maximilian Frank presents the results of the first large scale survey amongst psychology students conducted by the Open Science Working Group of the PsyFaKo. In this study, 1,397 psychology students in the German-speaking countries were surveyed to investigate the occurrence of QRPs in student projects and to assess the current state of academic teaching regarding the replication crisis and open science practices. Based on these findings we will discuss impulses for the development of teaching and have a look in the related positions papers of the PsyFaKo. The principles of openness, transparency, and collaboration need to play an important role in the academic teaching and are part of a generational change in the academic education of students.</p><p><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">About the speaker:</span></p><p>Maximilian Frank studied psychology at the Ludwig-Maximilians-University of Munich and graduated in the interdisciplinary master's program Human Factors in Engineering at the Technical University of Munich. Since 2022 he<br>is a doctoral candidate in the DFG priority program “META-REP” and conducts research on heterogeneity estimations in meta-analyses. As coordinator of the Open Science Working Group of the Psychologie-Fachschaften-Konferenz (PsyFaKo) he is committed to open research practices and their communication in academic teaching.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
