---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Big Little Lies: p-hacking and effective countermeasures"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Big Little Lies: p-hacking and effective countermeasures"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "June 10, 2022"
  end_date: "June 10, 2022"
  time: "14:30–16:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its fifth meeting to discuss an interesting paper about p-hacking strategies and effective countermeasures. The organisation team is happy to announce that the paper’s author, Angelika Stefan, will give an introductory talk to this session and participate in the open discussion afterwards:</p><p>Participants can use the following <strong>key questions</strong> to prepare for the discussion:</p><ul>
<li>What do you think: How prevalent are p-hacking-strategies in your field/community (e.g. in student thesis, in published research)?</li>
<li>Which potential solutions (described on pages 37-45) do you find the most convincing?</li>
<li>Which questions about QRPs do you still have? Which questions do you think are not answered by the scientific community, yet (both empirical questions e.g. specific prevalence rates and theoretical questions)?</li>
</ul>
<p><br>You can find a short abstract for the introductory talk by Angelika Stefan (University of Amsterdam) below:</p><h3>Big Little Lies: p-hacking and effective countermeasures</h3><p>A decade ago, John et al. (2012) found a high prevalence of questionable research practices (QRPs) among psychological researchers. This result was confirmed by many other surveys among researchers in the social sciences. QRPs range from accidental mistakes to clear scientific misconduct and its prevalence undermined the credibility of the social sciences. One of the most prominent QRPs is p-hacking which includes a broad range of different strategies to render non-significant testing results significant. But if QRPs and especially p-hacking are widespread, as previous research suggests: How problematic are the different strategies in fact? How big is the impact of different p-hacking-strategies in detail? And what countermeasures are most effective?</p><p>In this talk, Angelika Stefan will give a short, general introduction to QRPs. She will discuss p-hacking in more detail and distinguish it from other QRPs. Then, she will show some examples of simulations from this session’s paper that examined the impact of different p-hacking strategies. Based on the simulations’ results, possible countermeasures and solutions will be introduced and discussed.</p><h3>About the speaker:</h3><p>Angelika Stefan is a researcher and doctoral candidate at the University of Amsterdam and belongs to the Department of Psychological Methods within the Faculty of Social and Behavioural Sciences. She finished her Masters in Economic, Organizational and Social Psychology in 2018 at LMU Munich. Her work focuses on the application of Bayesian Statistics and the general dealing with methodological flexibility in the Social Sciences. She is an expert for Open Science, led many workshops on Open Science-related topics and organizes the ReproducibiliTea at her university in Amsterdam.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
