---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Better theory development as a response to the prevalence of QRPs"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Better theory development as a response to the prevalence of QRPs"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "July 29, 2022"
  end_date: "July 29, 2022"
  time: "14:30–16:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its ninth meeting to discuss an interesting paper on how better theory development could be an answer to current replicability problems. The organisation team is happy to announce that the paper’s author, Prof. Dr. Chris Donkin, will give an introductory talk to this session and participate in the open discussion afterwards:</p><p>Participants can use the following <strong>key questions</strong> to prepare for the discussion:</p><ul>
<li>How might the flexiblity of theories contribute to replicability problems?</li>
<li>What are the characteristics of good theories?</li>
<li>Is preregistration misguided to prevent QRPs? What could be arguments for and against such an opinion?</li>
</ul>
<p>You can find a short abstract for the introductory talk by Prof. Dr. Chris Donkin below:</p><h3>
<span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em;">Better theory development as a response to the prevalence of QRPs</span><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;"><br></span>
</h3><p><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em;">Concerns about so-called QRPs, and especially p-hacking, are typically based on concerns about false-positive statistical outcomes. However, the outcome of a statistical test is not equivalent to a scientific claim, and so elevated Type-I error rates do not speak directly to reduced replicability. We will explain why certain kinds of statistical analyses, including those forms of p-hacking that seem most egregious, will indeed lead to an inability to predict the outcome of future experiments. The problem, simply put, is that without sufficient scientific argument, any statistical analysis taken at face value is an ad hoc explanation, from which there is no good reason to expect to understand the world. We contrast such explanations with good theories and discuss what those are. Thinking about p-hacking from this perspective helps provide a way of deciding what kinds of analyses are good or bad, independent of whether they are p-hacked, ‘exploratory’, or ‘confirmatory’. </span></p><p><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">About the speaker:</span></p><p>Chris Donkin is a Professor of Computational Modelling in Psychology at LMU Munich. His work focuses on explaining cognitive phenomena, such as memory and decision-making, often relying on using mathematical and computational models as aids to help understand and test our theories.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
