---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Version control with Git/GitHub within RStudio"'
categories: 'Workshop'

# Event categories
event:
  title: '"Version control with Git/GitHub within RStudio"'
  description: ""
  categories:  'Workshop'
  date: "October 27, 2022"
  end_date: "October 27, 2022"
  time: "9:00-12:00"
  location:
    name: "Hybrid (Leopoldstraße 13, room 3322, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Open Science Initiative Psychology (OSIP) and the LMU Open Science Center offer a hands-on workshop for scientists of all career levels on the topic of Version Control on October 27, 2022 from 9:00 am to 12:00 pm (Instructor: Dr Malika Ihle, facilitator: Felix Henninger).</p><p>You will learn how to track and manage changes in software code, a.k.a. version control, with Git and GitHub within RStudio. This will make your own workflow more reproducible and allow you to code (or even write manuscripts) collaboratively.</p><p>The workshop consists in facilitated self-paced tutorials: <a href="https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub">https://github.com/lmu-osc/Introduction-RStudio-Git-GitHub</a> and <a href="https://github.com/lmu-osc/Collaborative-RStudio-GitHub">https://github.com/lmu-osc/Collaborative-RStudio-GitHub</a> which include the setting up and configuring of all software required.</p><p><strong>Participants</strong>: The targeted audience are complete novices regarding version control / Git, but who use RStudio at least occasionally. No R knowledge is necessary.</p><p><strong>Requirement</strong>: Participants must bring their own laptop with admin access and have an internet connection. Software will be installed as part of the workshop. No previous knowledge necessary.</p><p>Participation in the workshop is free and open to all LMU affiliated researchers. However, priority will be given to members of Departments sponsoring the Open Science Center (e.g. Department of Psychology). Non-members will receive confirmation whether their attendance is possible at least 2 days before the workshop.</p><p>The event will be held in English. </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
