---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Public Trust in Science and the Replication Crisis: Challenges and Opportunities for Science Communication"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Public Trust in Science and the Replication Crisis: Challenges and Opportunities for Science Communication"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "July 01, 2022"
  end_date: "July 01, 2022"
  time: "14:30–16:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its sixth meeting to discuss two interesting papers. The organisation team is happy to announce that the paper’s authors, Dr. Tobias Wingen and Marlene Altenmüller, will give an introductory talk to this session and participate in the open discussion afterwards:</p><p>Participants can use the following <strong>key questions</strong> to prepare for the discussion:</p><ul>
<li>How could researchers restore public trust in social sciences (damaged by the replication crisis)?</li>
<li>How should researchers inform a) the public and b) their students about the replication crisis in social sciences?</li>
<li>What role do self-criticism and doubt play in communicating one's research a) to the public and b) to students?</li>
</ul>
<p>You can find a short abstract for the introductory talks by Dr. Tobias Wingen and Marlene Altenmüller below:</p><h3>Public Trust in Science and the Replication Crisis: Challenges and Opportunities for Science Communication</h3><p>The replication crisis and scientific self-correction are central topics in the current psychological debate. However, less is known about how non-scientists (e.g., the public) react to these controversies.</p><p>In the first part of this talk, Tobias Wingen will present a series of studies showing that low replicability may damage public trust in psychological science. These studies further show that this damaged trust is difficult to repair. Overall, this line of work suggests that non-scientists react negatively to failed replications.</p><p>In the second part of the talk, Marlene Altenmüller will present studies that demonstrate no harm of researchers’ self-correction (i.e., self-criticism of prior research and intentions for reforms in future research) on the public’s trust in science. This line of work suggests, that non-scientists favour a critical stance towards science. The presenters look forward to a stimulating discussion, which may focus on similarities and differences of their approaches, implications for science communication and teaching, and future direction.</p><h3>About the speakers:</h3><p>Marlene Altenmüller</p><p>Marlene Altenmüller is a research associate with the social psychology group at LMU Munich. Her work focuses on trust in and within science and, more broadly, science reception (e.g., motivated science reception), as well as art reception (e.g., aesthetic experience and impact) and social justice (e.g., justice sensitivity). Marlene’s doctoral thesis – hot off the press – applies social psychological theories on trust, stereotypes, and self-disclosing communication in the domain of researchers’ science communication and laypeople’s trust in science.</p><p>Dr. Tobias Wingen</p><p>The work of Dr. Tobias Wingen focuses on trust in science and science communication, which he often studies from a social-cognitive perspective. A central topic of his work are determinants and consequences of trust in science. For example, his research showed that scientific quality control (such as peer-review or successful replication studies) fosters public trust in science. His work further demonstrated that trust in science, in turn, is a central predictor of various beneficial behaviours, such as protective behaviour during pandemics. Tobias recently completed his doctoral degree at the Social Cognition Center Cologne (University of Cologne) and is now a postdoctoral researcher in the Research Group on Health and Risk Communication at the Institute of General Practice and Family Medicine (University Hospital Bonn).</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
