---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Positionality statements - Should authors be more transparent about themselves?"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Positionality statements - Should authors be more transparent about themselves?"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "December 16, 2022"
  end_date: "December 16, 2022"
  time: "14:30–16:00"
  location:
    name: "Hybrid (Room 1307 at Leopoldstraße 13, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its twelfth meeting, the third one for this semester. It will already take place this Friday and we will discuss "Positionality statements". </p><p><strong>Procedure:</strong>  A member of our organising team will give a short introduction at the beginning to introduce the topic of this session. We will then continue with an open discussion in which you can contribute your own thoughts and questions.</p><p>It would be helpful to have read the announced paper, but there is no obligation to do so. If you do not have time to read the entire paper, we recommend that you focus on the end of the article, which begins with the heading "Moving Forward" (pages 1303-1306). This part contains a brief summary of the previous sections as well as the author's recommendations (e.g. including positionality statements in publications). We prepared the following <strong>key questions</strong> to guide you through the discussion and also provide some guidance while reading the paper. For each question, you can think about the suggestions from the paper, but also bring in your own ideas:</p><ul>
<li>Which information could (and should) be included in positionality statements?</li>
<li>What possible problems are the positionality statements aimed at? What other measures could help to solve these problems?</li>
<li>In which concrete way would the introduction of (mandatory) positionality statements change the scientific system and the scientific way of generating knowledge? What might be negative/positive consequences?</li>
</ul>
<p>Below, you can find a short abstract for the session.</p><h3>Positionality statements - Should authors be more transparent about themselves?</h3><p>Following the theme of this year's Journal Club "Pushing Open Science to its limits", the upcoming session is dedicated to a less common open research practice that may be of particular interest in the social sciences. In positionality statements, authors describe their own connection to the research topic/question. They might make aspects of their<br>own identity transparent (e.g. belonging to an ethnic group) or explain their interest in the topic. For example, researchers examining aspects of discrimination against a particular group could inform readers whether or not they themselves belong to the discriminated group. So far, this method has been more common among qualitative researchers, where it is often part of the researcher's general reflection on the methods used. Recently - also in the context of social, anti-discriminatory and epistemological debates - calls have been made to include such statements in quantitative research as well. In this session we want to briefly introduce the idea of such statements and openly discuss possible advantages and disadvantages.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, PhD Student at the Chair of Social Psychology</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
<li>Franka Etzel, Psychology Student at LMU Munich</li>
<li>Viktoria Wiegelmann, Psychology Student at LMU Munich</li>
<li>Gracia Prüm, Psychology Student at LMU Munich</li>
<li>Alp Kaan Aksu, Psychology and Informatics Student</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
