---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Julia - A fresh approach to scientific computing"'
categories: 'Workshop'

# Event categories
event:
  title: '"Julia - A fresh approach to scientific computing"'
  description: ""
  categories:  'Workshop'
  date: "September 11, 2023"
  end_date: "September 11, 2023"
  time: "14:30–17:30"
  location:
    name: "Hybrid (Ludwigstraße 25, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Julia is a high-level dynamic programming language designed for numerical and scientific computing, data analysis, machine learning, and more. Julia’s user-friendly interface, resembling popular languages like R, Python, and Matlab, makes it easily accessible for learners. Its focus on performance, however, enables computational speeds that often rival, or even surpass, those of low-level languages such as C or Fortran. Therefore, Julia is an ideal choice for large-scale data analysis and other computationally intensive tasks, as it can be orders of magnitude faster than R or Python.</p><p>In this workshop, we will introduce you to the basics of Julia and the key features setting it apart from other languages.</p><p><strong>Participants:</strong> This workshop is designed for R users who are interested in learning a new programming language or want to improve their skills in data analysis and scientific computing. No prior experience with Julia is required, but a understanding of R is recommended.</p><p><strong>Instructors: </strong>A team from the Max Planck Institute for Human Development, the Max Planck School of Cognition, and the Max Planck UCL Centre for Computational Psychiatry and Ageing Research will instruct this workshop: <a href="https://www.mpib-berlin.mpg.de/person/103737/2549" target="_blank">Dr. Aaron Peikert</a>, post-doctoral fellow, <a href="https://www.mpib-berlin.mpg.de/staff/maximilian-ernst" target="_blank">Maximilian Ernst</a>, PhD student, and <a href="https://www.mps-ucl-centre.mpg.de/people/126423" target="_blank">Moritz Ketzer</a>, PhD student.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
