---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"The Ideal of Preregistration and what warrants it"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"The Ideal of Preregistration and what warrants it"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "January 27, 2023"
  end_date: "January 27, 2023"
  time: "14:30–16:00"
  location:
    name: "Hybrid (Leopoldstraße 13, room 3322, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its 13th meeting. The organisation team is happy to  welcome Aaron Peikert (Max-Planck-Institute Berlin) as our guest who will give the introductory presentation and participate in the open discussion afterwards.</p><p>The meeting is dedicated to the topic "The Ideal of Preregistration and what warrants it". Aaron Peikert has recently uploaded a draft for a paper on "Why does preregistration increase the persuasiveness of evidence? A Bayesian rationalization". During our meeting, he will present some of his ideas from this draft and take up further debates around the issue of preregistration. Below you will find a short abstract that provides more information on the topic of the presentation.</p><p>We prepared the following <strong>key questions</strong> to guide you through the discussion and also provide some guidance while reading the paper. The presentation will take up some of the ideas from the paper, but present them in a more "discussion-friendly" way and go beyond the topic. For each question, you can think about the suggestions from the paper, but also bring in your own ideas:</p><ul>
<li>What are objections to preregistration?</li>
<li>To what extent can incomplete preregistrations (e.g. only regarding study variables, but without an exact analysis plan) be useful?</li>
<li>What is the actual purpose of preregistration?</li>
</ul>
<p>You can find a short abstract for the introductory talk by Aaron Peikert below:</p><h3><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">The Ideal of Preregistration and what warrants it </span></h3><p>The replication crisis spurned many researchers to preregister their analyses before acquiring data. However, there is no agreement on what preregistration should accomplish and why it is uniquely suited to these goals. A widespread view is that preregistration should limit how much the data may influence the hypotheses tested on the same data (i.e., restrict researchers' degrees of freedom)). If no such influence occurs, an analysis is generally considered confirmatory. Consequently, many researchers believe that only confirmatory studies benefit from preregistration.</p><p>In this presentation, Aaron Peikert argues that limiting preregistration to confirmatory research is unnecessarily restrictive. To that end, he will suggest how to formalize the objective of preregistration and aim to demonstrate that exploratory studies also benefit from the practice. Lastly, implications for the practice of preregistration will be discussed.</p><p><span style="color: #404040; font-family: verdana, helvetica, arial, sans-serif; font-size: 1em; font-weight: bold;">About the speaker:</span></p><p>Aaron Peikert is a PhD student at the Max-Planck-Institute for Human Development in Berlin and has been an Open Science enthusiast since his bachelor's degree. His work focuses on preregistration, reproducible workflows, structural equation models and machine learning approaches for nested/ hierarchical data.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, Psychology Student at LMU Munich</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
<li>Franka Etzel, Psychology Student at LMU Munich</li>
<li>Viktoria Wiegelmann, Psychology Student at LMU Munich</li>
<li>Gracia Pruem, Psychology Student at LMU Munich</li>
<li>Alp Kaan Aksu, Psychology Student at LMU Munich</li>
<li>Finia Loeb, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
