---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Theoretical Frameworks as Lifesavers for Psychology"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Theoretical Frameworks as Lifesavers for Psychology"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "June 23, 2023"
  end_date: "June 23, 2023"
  time: "14:30–16:00"
  location:
    name: "Hybrid (Leopoldstraße 13, room 3322, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Journal Club: “ReproducibiliTea” at LMU Munich continues with its 18th meeting, the sixth one for this semester. It will take place this Friday and we will talk about the Theoretical Frameworks. Following a quick introduction into Muthukrishna et. al. paper "A problem in theory", that stresses the importance of cumulative theoretical framework in order to mitigate the replication crisis and to pave the way toward a more general theory of human behaviour, we would like to discuss whether these frameworks could actually be Lifesavers for Psychology.</p><p><strong>Procedure:</strong> One member of our organising team will introduce (approx. 20 minutes) the paper. We will then continue with an open discussion where you can contribute your own thoughts and questions. Finally, there will be time to get to know each other and talk in smaller groups.</p><h2>Concept of the Journal Club</h2><p>The interdisciplinary journal club “ReproducibiliTea” is launched every 3-4 weeks and addresses main questions and current topics concerning Open Science and the credibility of research findings. The idea - originated from Great Britain - was already developed in many other countries using the same name. During on-site meetings tea, juice and small snacks are provided to live up to the slogan. However, some meetings are held online due to organisational reasons. No matter where the sessions take place, everybody is welcome to bring their own food and drinks and thus connect the journal club with their lunch break.</p><p>The Journal Club consists of open talk sessions for discussing Open Science, reproducibility, and other related issues and is explicitly open to all disciplines and institutions to create the most interesting interchange. Each session starts with a short talk about the paper and then continues with an open discussion in which you can contribute your own thoughts and questions.</p><p>During a longer break between 2020 and 2021, the concept was slightly revised, and the organisation team decided to invite the speaker(s) of the respective paper that is discussed in each session. The author herself/himself starts with the introductory talk including a short summary of the paper. Afterwards, there is enough time for direct interaction with the author(s) and, as before, an open discussion with all of the participants.</p><p>You are warmly welcome to join the next meetings. You can simply send an e-mail to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> to join the mailing list to get information about the next meetings and chosen papers. For each session it would be helpful to have read the announced paper, but there is no obligation to do so.</p><p>The organisation team is looking forward to seeing you at one of the next Journal Club sessions.</p><p>Organisation team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Medical Student at LMU Munich</li>
<li>Stephan Nuding, PhD Student at the Chair of Social Psychology</li>
<li>Leonhard Schramm, Psychology Student at LMU Munich</li>
<li>Franka Etzel, Psychology Student at LMU Munich</li>
<li>Viktoria Wiegelmann, Psychology Student at LMU Munich</li>
<li>Gracia Pruem, Psychology Student at LMU Munich</li>
<li>Finia Loeb, Psychology Student at LMU Munich</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
