---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: 'Love Data Week: a series of events on research data management'
categories: ''

# Event categories
event:
  title: 'Love Data Week: a series of events on research data management'
  description: ""
  categories:  ''
  date: "January 26, 2023"
  end_date: "January 26, 2023"
  time: "NA"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: '"Love Data Week 2023'
    detail: ""
  language:
    primary: "German and English"
    primary-code: "de"
    detail: "de/en"
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Check out the programme for the Love Data Week 2023!</p><h2>Forschungsdatenmanagement: Grundlagen und Hilfsmittel</h2><p><span style="text-decoration: underline;">Montag, 13.02.2023 13:00 - 14:00 Uhr</span><br><strong>Abstract</strong>: Forschungsdaten bilden die Grundlage wissenschaftlicher Arbeit. Auch das Forschungsdatenmanagement wird in diesem Zusammenhang immer bedeutender. In dieser Einführungsveranstaltung werden die wichtigsten Grundlagen aufgezeigt und verfügbare Ressourcen sowie Hilfsmittel – wie z. B. die Angebote von FDM-Bayern.org – vorgestellt.<br><strong>Sprache</strong>: deutsch<br><strong>Teilnahmebedingungen</strong>: öffentlich und für alle Zielgruppen<br><strong>Registrierung</strong>: <a href="https://lmu-munich.zoom.us/meeting/register/tJEtdemgqD0pHdIC7dQRgnr9IQmL6YtmcG7-" target="_blank">https://lmu-munich.zoom.us/meeting/register/tJEtdemgqD0pHdIC7dQRgnr9IQmL6YtmcG7-</a><br><em>Durchgeführt von: ITG und UB der LMU (Christiane Bayer, Vanessa Gabriel, Dr. Martin Spenger)</em></p><h2>Metadaten, PID und Normdaten</h2><p><span style="text-decoration: underline;">Montag, 13.02.2023 15:00 – 16:00 Uhr</span><br><strong>Abstract</strong>: Der Vortrag richtet sich vor allem an FDM-Neulinge in der Forschung und dient der Klärung von grundlegenden Konzepten und Ideen im Forschungsdatenmanagement. Die Idee der digitalen Sichtbarkeit im Forschungsalltag soll hier vorgestellt und durch das Anlegen einer ORCID iD umgesetzt werden.<br><strong>Sprache</strong>: deutsch<br><strong>Teilnahmebedingungen</strong>: öffentlich und für alle Zielgruppen<br><strong>Registrierung</strong>: <a href="https://lmu-munich.zoom.us/meeting/register/tJUkdumvqT8vGtZxmnvmCYA6Tt5ybt7spyL-" target="_blank">https://lmu-munich.zoom.us/meeting/register/tJUkdumvqT8vGtZxmnvmCYA6Tt5ybt7spyL-</a><br><em>Durchgeführt von: ITG (Christiane Bayer)</em></p><h2>Coffee Lecture "Data journals and data publication"</h2><p><span style="text-decoration: underline;">Dienstag, 14.02.2023 13:00 – 13:45 Uhr</span><br><strong>Abstract</strong>: Open short lecture for interested researchers and students, with Q&amp;A session.<br><strong>Topics</strong>: When should one consider publishing data? Data publication prerequisites (legal hurdles, licences, preparatory work), publishing options; what are data journals?<br><strong>Sprache</strong>: englisch<br><strong>Teilnahmebedingungen</strong>: öffentlich und für alle Zielgruppen<br><strong>Registrierung</strong>: <a href="https://ub.fau.de/schulungen/a-short-introduction-to-data-publishing-and-data-journals/" target="_blank">https://ub.fau.de/schulungen/a-short-introduction-to-data-publishing-and-data-journals/ </a>(Informationen mit Zoom-Einwahldaten, keine Registrierung erforderlich)<br><em>Durchgeführt von: UB FAU (Dr. Jürgen Rohrwild)</em></p><h2>Veranstaltung für Bibliotheksmitarbeitende zu "Datenrecherche und Nachweissysteme"</h2><p><span style="text-decoration: underline;">Mittwoch, 15.02.2023 9:15 – 10:45 Uhr</span><br><strong>Abstract</strong>: Während es für die Suche nach klassischen und elektronischen Publikationen verschiedene etablierte Discovery-Lösungen gibt, ist die Situation bei Forschungsdaten unübersichtlicher. In einigen Disziplinen gibt es zentrale Datenbanken, mit denen die Fachcommunity vertraut ist, in anderen Fächern sind Datensätze nur schwer zu lokalisieren, da es nur wenige Nachweisinstrumente gibt. In dieser Veranstaltung geht es weniger um die konkrete Suche nach speziellen Datensätzen und –banken. Vielmehr soll ein allgemeiner Überblick über die nach wie vor bestehenden Probleme bei der Datenrecherche und potenziell nützliche Nachweisinstrumente gegeben werden.<br><strong>Sprache</strong>: deutsch<br><strong>Teilnahmebedingungen</strong>: für Bibliotheksmitarbeitende der FAU und LMU<br><strong>Registrierung</strong>: <a href="https://www.studon.fau.de/studon/ilias.php?baseClass=ilrepositorygui&cmd=infoScreenGoto&ref_id=4923482" target="_blank">https://www.studon.fau.de/studon/ilias.php?baseClass=ilrepositorygui&cmd=infoScreenGoto&ref_id=4923482</a> (FAU), per E-Mail an Beschäftigte (UB der LMU)<br><em>Durchgeführt von: UB FAU (Dr. Jürgen Rohrwild)</em></p><h2>Datenmanagementpläne einfach erstellen mit RDMO</h2><p><span style="text-decoration: underline;">Donnerstag, 16.02.2023 15:00 – 16:00 Uhr</span><br><strong>Abstract</strong>: Die strukturierte Planung eines Forschungsvorhabens und die Verwaltung der eigenen Daten bringen im Forschungsalltag viele Vorteile mit sich. Worauf man bei der Erstellung eines Datenmanagementplans achten muss und wie webbasierte Werkzeuge wie der Research Data Management Organizer (RDMO) zur Arbeitserleichterung eingesetzt werden können, wird in dieser Veranstaltung gezeigt.<br><strong>Sprache</strong>: deutsch<br><strong>Teilnahmebedingungen</strong>: öffentlich und für alle Zielgruppen<br><strong>Registrierung</strong>: <a href="https://lmu-munich.zoom.us/meeting/register/tJMuf-mrrzoiGdZFwCNMHVT7tm2qVnE0mb6c" target="_blank">https://lmu-munich.zoom.us/meeting/register/tJMuf-mrrzoiGdZFwCNMHVT7tm2qVnE0mb6c</a><br><em>Durchgeführt von: UB der LMU (Laura Meier, Vanessa Gabriel)</em></p><h2>Introduction to Open Data and RDM Services at LMU</h2><p><span style="text-decoration: underline;">Freitag, 17.02.2023 10:00 – 12:00 Uhr</span><br><strong>Abstract</strong>: The workshop is kicked off with an introduction on the relevance of Open Research Data by the Open Science Center. The second part by the LMU Unit for Research Funding puts the focus on resources at LMU which help you to increase the transparency of your research and fulfill the guidelines of research funders. The workshop concludes with a short introduction of the RDM Help Desk at the University Library and a subject specific RDM service for the Humanities at the LMU which is offered in collaboration with the LMU Center for Digital Humanities. There will also be enough time for Q&amp;A after each presentation.<br>After registration you are able to join the full workshop or just for one of the individual presentations:</p><ul>
<li>10:00 – 10:30 Introduction to Open Research Data (Prof. Dr. Felix Schönbrodt)</li>
<li>10:30 – 11:00 RDM Resources at LMU and relevance for research funding (Dr. Veit Schwab, Dr. Florian Schreck)</li>
<li>11:00 – 11:30 RDM Help Desk at LMU (Dr. Martin Spenger)</li>
<li>11:30 – 12:00 Subject Specific RDM for the Humanities (Christiane Bayer, Dr. Martin Spenger)</li>
</ul>
<p><strong>Sprache</strong>: englisch<br><strong>Teilnahmebedingungen</strong>: öffentlich, teilweise mit Fokus auf LMU-Angebote<br><strong>Registrierung</strong>: <a href="https://lmu-munich.zoom.us/meeting/register/tJEsce6gqT4sG9SVj8Wu2L8J51YfyP6Eu4K1" target="_blank">https://lmu-munich.zoom.us/meeting/register/tJEsce6gqT4sG9SVj8Wu2L8J51YfyP6Eu4K1</a><br><em>Durchgeführt von: Open Science Center (OSC), Referat VIII.3 (Forschungsförderung), UB der LMU und ITG</em></p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
