---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: 'Introduction to credible research'
categories: 'Lecture'

# Event categories
event:
  title: 'Introduction to credible research'
  description: ""
  categories:  'Lecture'
  date: "February 27, 2023"
  end_date: "February 27, 2023"
  time: "15:00-16:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Lecture'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Do you want to gain more trust in the research that you do, and make it as credible as it can be in the eyes of your peers, the public, and funding agencies?<br>Join and learn about creating:</p><ul>
<li>statistical plans in advance of collecting data to prevent biases in analyses, with the help of preregistration and data simulation;</li>
<li>reproducible workflows, so you can spot your mistakes in your data wrangling or analyses, with essential programming skills;</li>
</ul>
<p>This short online lecture will be an introduction to several useful open research practices and tools – and can be followed-up by several workshops delivered on demand by the LMU Open Science Center coordinator Dr Malika Ihle. One workshop is already scheduled on March 7, 9:00-12:00: Version control with Git and GitHub within RStudio (see <a href="../workshop_version_control2/index.html" title='Workshop: "Version control with Git/GitHub within RStudio"'>here</a>).</p><p><strong>Participants</strong>: Open for all researchers</p><p><strong>Instructor</strong>: Dr. Malika Ihle (LMU Open Science Center coordinator)</p><p>The event will be held in English. </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
