---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Sensitivity Analyses: Why and how?"'
categories: 'Workshop'

# Event categories
event:
  title: '"Sensitivity Analyses: Why and how?"'
  description: ""
  categories:  'Workshop'
  date: "July 05, 2023"
  end_date: "July 05, 2023"
  time: "10:00–12:00"
  location:
    name: "Hybrid (Room 3322, Leopoldstr 13, Munich and on Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The Open Science Initiative Psychology (OSIP) and the LMU Open Science Center offer a workshop for scientists of all career levels (from MSc) from any quantitative disciplines, on the topic of Sensitivity Analyses on July 5, 2023 from 10:00 am to 12:00 pm, in room 3322 in Leopoldstr 13, Munich and on Zoom.</p><p>Sensitivity Analyses: Why and how?<br>Typically, there is more than one right way to evaluate empirical data. One way to deal with this methodological flexibility are sensitivity analyses. In this short workshop, we will discuss when sensitivity analyses can be useful, what they can look like in practice, and how they can be embedded in scientific publications.</p><p>Participation in the workshop is free and open to all. Priority will be given to, in order, members of Departments sponsoring the Open Science Center (Department of Psychology, Business Administration, Biology), other LMU members, and non-LMU members. Non-members will receive confirmation whether their attendance is possible at least 2 days before the workshop.</p><p>Instructor: Dr Angelika Stefan (Chair of Computational Modeling in Psychology, LMU)</p><p>The event will be held in English, unless there are only German native speakers in the room!</p><ul style="list-style-type: square;"><li>
</li></ul>
<div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
