---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Making Tacit Knowledge Open - Part I: Practices and Practicalities of Peer Review"'
categories: 'Panel Discussion Series'

# Event categories
event:
  title: '"Making Tacit Knowledge Open - Part I: Practices and Practicalities of Peer Review"'
  description: ""
  categories:  'Panel Discussion Series'
  date: "May 27, 2024"
  end_date: "May 27, 2024"
  time: "16:00-18:00"
  location:
    name: "Hybrid (Leopoldstraße 13, room 3322 and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Panel Discussion Series'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>MAKING TACIT KNOWLEDGE OPEN – A Panel Discussion Series<br>Academia is full of tacit knowledge that is difficult to access for early career researchers and first-generation academics who do not (yet) have large academic networks. In our new panel discussion series, we try to make this tacit knowledge open by asking the relevant questions to a diverse set of experts.</p><p>PRACTICES AND PRACTICALITIES OF PEER REVIEW<br>Most researchers spend a significant amount of time and effort on peer reviewing. However, there is large variability in peer reviewing practices and little guidance for early career researchers on the topic. For this panel discussion, we assemble experts from different fields of psychology to talk about their experiences with peer review from a reviewer’s and/or editor’s perspective. We talk about how they developed their own style of peer reviewing, what they consider a good peer review, tips and tricks for peer-reviewing efficiently, and how their personal scientific philosophy influences their peer reviews.</p><p><strong>Panel Members: </strong></p><ul>
<li>Dr. Marlene Altenmüller (Social Psychology)</li>
<li>Dr. Peter Edelsbrunner (Learning Sciences, ETH Zürich)</li>
<li>Dr. Nathan Evans (Computational Modeling in Psychology)</li>
<li>Dr. Florian Pargent (Psychological Methods and Assessment)</li>
<li>Prof. Dr. Tobias Staudigl (Cognitive Neuropsychology)</li>
<li>Dr. Charlotte Wittekind (Clinical Psychology)</li>
</ul>
<p><strong>Target audience:</strong> Anyone curious about how other people write peer reviews</p><p><strong>Prerequisites:</strong> None (no peer reviewing experience required)</p><p><strong>Max. number of participants:</strong> No maximum</p><p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
