---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Epistemic Foundations and Limitations of Statistics and Science - Explaining the Replication Crisis?"'
categories: 'Workshop'

# Event categories
event:
  title: '"Epistemic Foundations and Limitations of Statistics and Science - Explaining the Replication Crisis?"'
  description: ""
  categories:  'Workshop'
  date: "November 22, 2024"
  end_date: "November 22, 2024"
  time: "9:00-18:00"
  location:
    name: "Munich"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The aim of the workshop is to bring together statisticians, philosophers of science, and other interested researchers to discuss aspects of <strong>Open Science</strong> and the <strong>replication crisis</strong> from an epistemic perspective on the foundations and limitations of statistics.</p><p>The replication crisis is usually explained by misaligned incentive structures in the scientific system ("publish or perish"). Another important, but underrated, aspect is that researchers -- even statisticians -- tend to <strong>disregard important epistemic foundations of statistics</strong>. This lack of principle (or knowledge) effectively contributes to questionable research practices, statistical rituals, delusions and fallacies about what statistics and science can achieve. In the age of big data and foundation models, the importance of these topics is greater than ever before.</p><p>With keynotes by select speakers and ample time for discussion, we will address the question why the inappropriate use of statistical methods (most prominently, statistical testing) is still so prevalent, despite warnings that have been voiced for decades.</p><p><strong>Keynote talks:</strong></p><ul>
<li>Sabina Leonelli (TU Munich), was recently appointed Professor for Philosophy and History of Science and Technology at TUM. She works on the philosophy of data-intensive science; in particular, the impact of big and open data on research and society in general.</li>
<li>Uwe Saint-Mont (HS Nordhausen),  holds a chair at the Department of Economics and Social Sciences. He works on statistical theory, philosophy of statistics, and philosophy of science.</li>
</ul>
<p><strong>Other talks:</strong></p><ul>
<li>Walter Radermacher (Advisory Board on Ethics of the International Statistical Institute and LMU Munich), is a Professor of Statistics at LMU. Additionally, he serves as the Advisory Board Chair of the International Statistical Institute (ISI). Furthermore, he has experience in public administration at national and European levels, having served as President of the German Statistical Office (destatis), Director General of Eurostat and Chief Statistician of the European Union, and Chair of the destatis Commission Future Statistics. He works on statistics, sustainable development, governance, ethics, and data analysis.</li>
<li>Rudolf Seising (Deutsches Museum), currently chairs the BMBF research project "Eine Geschichte der KI in der BRD". He works on the history of science and artificial intelligence.</li>
<li>Michael Schomaker (LMU Munich), is a Professor for Biostatistics working under the German Research Foundation's Heisenberg Program. He works on the appropriate use of modern causal inference methods.</li>
</ul>
<div><strong>Registration:</strong></div><div><strong><br></strong></div><div>Participation is <span style="text-decoration: underline;">open to everyone and free of charge</span>. Seats will be given on a first-register, first-serve basis.</div><p>To join the discussion, <strong>please register at <a href="https://www.pretix.osc.lmu.de/lmu-osc/osis2024/">https://www.pretix.osc.lmu.de/lmu-osc/osis2024/</a> by October 31st.</strong></p><p>The current program allows some room for further talks – please reach out to <a class="g-link-mail" href="mailto:epix.workshop@stat.uni-muenchen.de" title="Send email to: epix.workshop@stat.uni-muenchen.de">epix.workshop@stat.uni-muenchen.de</a> if you would like to add your perspective to the workshop.</p><p>Looking forward to seeing you at EPIX!</p><p><strong>Contact:</strong></p><p>If you have any questions, please do not hesitate to contact <a class="g-link-mail" href="mailto:epix.workshop@stat.uni-muenchen.de" title="Send email to: epix.workshop@stat.uni-muenchen.de">epix.workshop@stat.uni-muenchen.de</a>.</p><ul style="list-style-type: square;"><li>
</li></ul>
<div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
