---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"LMU Wikipedia Editathon"'
categories: 'Hacky Hour'

# Event categories
event:
  title: '"LMU Wikipedia Editathon"'
  description: ""
  categories:  'Hacky Hour'
  date: "November 25, 2024"
  end_date: "November 25, 2024"
  time: "16:30-18:00"
  location:
    name: "Wikipedia Munich, Angertorstraße 3"
    address: ""
    map_url: ""
  format:
    type: 'Hacky Hour'
    detail: ""
  language:
    primary: "English/German"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>The LMU is an important part of life in Munich, but still many of the parts that make up this large project are not well documented on Wikimedia projects like Wikipedia and Wikidata. This hinders public understanding of how such a large research university works. If you are interested in helping to better document the different teams, institutes, and research projects that define the LMU, this "LMU Editathon" will teach you how to do exactly that. No prior knowledge required!</p><p><em>Die LMU ist ein wichtiger Bestandteil des Münchner Lebens, doch viele ihrer Teile, die dieses große Projekt ausmachen, sind auf Wikimedia-Projekten wie Wikipedia und Wikidata noch nicht ausreichend dokumentiert. Dies erschwert das öffentliche Verständnis darüber, wie eine so große Forschungsuniversität funktioniert. Wenn Sie daran interessiert sind, zur besseren Dokumentation der verschiedenen Teams, Institute und Forschungsprojekte, die die LMU definieren, beizutragen, wird Ihnen dieser "LMU Editathon" genau zeigen, wie Sie das tun können. Vorkenntnisse sind nicht erforderlich!</em></p><p><strong>Please bring/Mitbringen:</strong></p><p>Computers are available, but you can also bring your own laptop if you prefer, as there is Wi-Fi available.</p><p><em>Rechner stehen zur Verfügung, aber wer lieber an seinem eigenen Notebook arbeitet, kann es mitbringen, es gibt WLAN.</em></p><p><strong>Costs/Kosten:</strong></p><p>Participation in the event is free of charge; a donation jar is available for voluntary contributions to support WikiMUC.</p><p><em>Die Teilnahme an der Veranstaltung ist kostenlos; ein Spendenglas nimmt gerne freiwillige Beiträge zum Unterhalt des WikiMUC entgegen.</em></p><p><strong>Agenda/Ablauf:</strong></p><ul>
<li>Short introduction and description of tasks</li>
<li><em>Kurze Einführung und Beschreibung der Aufgaben</em></li>
<li>Visualization of the state of LMU representation across different dimensions (e.g., Professors total vs. Wikidata vs. Wikipedia)</li>
<li><em>Visualisierung des Stands der LMU-Repräsentation in verschiedenen Dimensionen (z.B. Gesamtanzahl der ProfessorInnen vs. Wikidata vs. Wikipedia)</em></li>
<li>Editing LMU institutes, people, and projects in the Wikipedia and Wikidata projects</li>
<li><em>Editieren von Instituten, Personen und Projekten der LMU in den Projekten Wikipedia und Wikidata</em></li>
<li>Pizza!</li>
<li>Presentation of results</li>
<li><em>Präsentation der Ergebnisse</em></li>
</ul>
<p><strong>Questions and Requests/Fragen und Wünsche:</strong></p><p>Questions and requests regarding the event can be sent to <a class="g-link-mail" href="mailto:wikimuc@wikipedia.de" title="Send email to: wikimuc@wikipedia.de">wikimuc@wikipedia.de</a> or posted in advance on the <a href="https://de.wikipedia.org/wiki/Wikipedia:WikiMUC/2024-11-25_LMU-Editathon">discussion page</a> of the Wikipedia event page (for those with an already existing Wikipedia account).</p><p><em>Fragen und Wünsche zu der Veranstaltung können vorab an <a class="g-link-mail" href="mailto:wikimuc@wikipedia.de" title="Send email to: wikimuc@wikipedia.de">wikimuc@wikipedia.de</a> gesendet werden oder auf der <a href="https://de.wikipedia.org/wiki/Wikipedia_Diskussion:WikiMUC/2024-11-25_LMU-Editathon">Diskussionsseite</a> der Wikipedia Eventpage eingetragen werden (für diejenigen, die bereits einen Wikipedia Account besitzen).</em></p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
