---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Reviewing essential computing skills for reproducible workflow”'
categories: 'Hacky Hour'

# Event categories
event:
  title: '"Reviewing essential computing skills for reproducible workflow”'
  description: ""
  categories:  'Hacky Hour'
  date: "September 30, 2024"
  end_date: "September 30, 2024"
  time: "16:30-18:00"
  location:
    name: "Wikipedia Munich, Angertorstraße 3"
    address: ""
    map_url: ""
  format:
    type: 'Hacky Hour'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>In this session, we will welcome newcomers (with pastries!) and revisit essential computing skills for reproducible workflow.</p><p>After our recent open science summer school, we shared several self-paced tutorials:</p><ul>
<li>Introduction to R: <a href="https://lmu-osc.github.io/introduction-to-R/">https://lmu-osc.github.io/introduction-to-R/</a>
</li>
<li>Version control with Git within RStudio: <a href="https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/">https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/</a> &amp; <a href="https://lmu-osc.github.io/Collaborative-RStudio-GitHub/">https://lmu-osc.github.io/Collaborative-RStudio-GitHub/</a>
</li>
<li>Literate programming with Quarto: <a href="https://lmu-osc.github.io/introduction-to-Quarto/">https://lmu-osc.github.io/introduction-to-Quarto/</a>
</li>
<li>R package management system renv: <a href="https://lmu-osc.github.io/introduction-to-renv/">https://lmu-osc.github.io/introduction-to-renv/</a>
</li>
<li>Introduction to Zotero as reproducible citation management system: <a href="https://lmu-osc.github.io/introduction-to-zotero/">https://lmu-osc.github.io/introduction-to-zotero/</a>
</li>
<li>Code publishing: <a href="https://lmu-osc.github.io/code-publishing/">https://lmu-osc.github.io/code-publishing/</a>
</li>
</ul>
<p>and more, on the LMU Open Science Center GitHub organisation: <a href="https://github.com/lmu-osc">https://github.com/lmu-osc</a><br>Whether you have followed these tutorials during one of our workshops, on your own, or learn about these topics elsewhere, you are invited to bring your questions or implementation problems along to get help from others!</p><p>For instance,</p><ul>
<li>you have learned R but are confused between base R and the tidyverse? Or can’t find the equivalent of your favorite Python hack?</li>
<li>you have learned version control with GitHub, but need to use the LMU GitLab to secure sensitive data and code?</li>
<li>you have started to write your manuscripts with Quarto to alternate plain language and R/Python analyses but struggle to integrate your bibliographic references efficiently or cross reference your figures?</li>
<li>you want to review package management systems or discuss licenses for data and code?</li>
<li>you want a second pair of eyes to look at your code, and engage in reciprocal peer code review?</li>
</ul>
<p>Join a group of reproducible research enthusiasts helping each other by sharing pieces of expertise or by searching for solutions together!</p><p> </p><p><strong>Sessions’ agenda:</strong></p><ul>
<li>Brief round of introductions and description of the problems you’ll be working on during that session</li>
<li>Formation of possible groups or tandems, if participants have tips to exchange on certain topics</li>
<li>Hack</li>
<li>Wrap-up: progress and next steps</li>
</ul>
<p>Learn more about the Hacky Hour initiative <a href="../../meetups/hackyhour/index.html" title="Hacky Hour">here</a>.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
