---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"How to review from an Open Science perspective"'
categories: 'Workshop'

# Event categories
event:
  title: '"How to review from an Open Science perspective"'
  description: ""
  categories:  'Workshop'
  date: "January 08, 2024"
  end_date: "January 08, 2024"
  time: "15:00–16:00"
  location:
    name: "Leopoldstraße 13, room 3322, Munich"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<h3>Abstract</h3><p>Reviewers have a central role in keeping up quality standards and in establishing implicit and explicit norms of academia.<br>Doing this unpaid voluntary work is vital part of academic functioning (including the much-trumpeted self-correction in science) and can be a powerful lever for improving credibility of published research. I will give a short overview of recent developments, including:</p><ul>
<li>the „Peer Reviewer’s Openness (PRO) initiative“</li>
<li>the pros and cons of open peer review</li>
<li>New publishing communities that organize open peer review without commercial publishers</li>
<li>personal reviewing standards and pledges.</li>
</ul>
<p>There will be plenty of room for discussion; for example on the specific challenges for early career researchers might face.</p><p><strong>Target audience</strong>: researchers from all empirical fields, all career stages.</p><p><strong>Logistics</strong>: There are no prerequisites. The format of the session is hybrid (you can attend online or in person). The event will be held in English. Participation in the workshop is free and open to all.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
