---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Reproducible computational environment"'
categories: 'Hacky Hour'

# Event categories
event:
  title: '"Reproducible computational environment"'
  description: ""
  categories:  'Hacky Hour'
  date: "April 22, 2024"
  end_date: "April 22, 2024"
  time: "16:30-18:00"
  location:
    name: "Wikipedia Munich, Angertorstraße 3"
    address: ""
    map_url: ""
  format:
    type: 'Hacky Hour'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Are you using programming languages such as R or Python? Are you, or your collaborators, sometimes struggling to get the same results on a different computer?</p><p>Are you still searching for an optimal way to keep track of your computational environments and packages versions?</p><p>In this session, we will discuss the benefits of reproducible computational environments and share tips on how to use the most common environment management tools.</p><p><strong>Possible beginner resources to prepare your session’s hack:</strong></p><ul>
<li>
<a href="https://osf.io/xp9zn/">https://osf.io/xp9zn/</a> (8 mins demo to various tools, e.g. renv, conda, docker, binder)</li>
<li>Using binder with quarto: <a href="https://quarto.org/docs/projects/binder.html">https://quarto.org/docs/projects/binder.html</a>
</li>
</ul>
<p><strong>Sessions’ agenda:</strong></p><ul>
<li>Brief round of introductions and description of the problems you’ll be working on during that session</li>
<li>Formation of possible groups or tandems, if participants have tips to exchange on certain topics</li>
<li>Hack</li>
<li>Wrap-up: progress and next steps</li>
</ul>
<p>Learn more about the Hacky Hour initiative <a href="../../meetups/hackyhour/index.html" title="Hacky Hour">here</a>.</p><p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
