---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Researcher Degrees of Freedom"'
categories: 'ReproducibiliTea Journal Club'

# Event categories
event:
  title: '"Researcher Degrees of Freedom"'
  description: ""
  categories:  'ReproducibiliTea Journal Club'
  date: "June 05, 2024"
  end_date: "June 05, 2024"
  time: "12:30-14:00"
  location:
    name: "Leopoldstraße 13, room 3322"
    address: ""
    map_url: ""
  format:
    type: 'ReproducibiliTea Journal Club'
    detail: ""
  language:
    primary: "German"
    primary-code: "de"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>In unserer 4. Session für dieses Sommersemester werden wir über Researcher Degrees of Freedom diskutieren. Unter Researchers Degrees of Freedom (RDFs) versteht man die Flexibilität, die Forscher beim Studiendesign, der Durchführung von Experimenten und der Datenanalyse haben. Verschiedene Entscheidungen während des Forschungsprozesses können zu erheblichen Unterschieden in den Studienergebnissen führen.</p><p><strong>Ablauf: </strong>Zu Beginn der Sitzung stellen euch zwei Mitglieder des Orgateams, Finia Loeb und Gracia Prüm, das Paper vor (ca. 20 Min). Im Anschluss werden wir über das Paper und das Thema Researcher Degrees of Freedom diskutieren (ca. 70 min). Ihr dürft auch gerne während des Vortrags eure Gedanken äußern oder Fragen stellen.</p><p><strong>Über den Journal Club: </strong><a href="https://www.osc.uni-muenchen.de/members/reproducibilitea/index.html">Hier</a> findet ihr mehr Informationen über das Konzept des Journal Clubs.</p><p>Ihr seid herzlich eingeladen, an unseren kommenden Treffen teilzunehmen! Um auf dem Laufenden zu bleiben und Benachrichtigungen über unsere Sessions und die ausgewählten Artikel zu erhalten, könnt ihr unsere Mailingliste abonnieren, entweder indem ihr auf den folgenden Link klickt, <a href="https://lists.lrz.de/mailman/listinfo/reproducibilitea">https://lists.lrz.de/mailman/listinfo/reproducibilitea</a>, oder indem ihr uns eine E-Mail an <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> schreibt. Es ist nicht erforderlich, das behandelte Paper vor jeder Sitzung gelesen zu haben, es könnte allerdings von Vorteil sein.</p><p>Wir freuen uns, euch bei einer unserer nächsten Journal-Club-Sitzungen zu sehen!</p><p>Organisationsteam:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Studentin in Medizin und Masterstudentin in Psychologie</li>
<li>Viktoria Wiegelmann, Bachelorstudentin in Psychologie</li>
<li>Gracia Prüm, Bachelorstudentin in Psychologie</li>
<li>Finia Loeb, Bachelorstudentin in Psychologie</li>
<li>Alp Kaan Aksu, Bachelorstudent in Psychologie und Informatik</li>
<li>Julian Lange, Doktorand in Statistik</li>
</ul>
<p> </p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
