---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"The Good, the Bad and the Inbetween - The many facets of quality in scholarly publishing"'
categories: 'Discussion'

# Event categories
event:
  title: '"The Good, the Bad and the Inbetween - The many facets of quality in scholarly publishing"'
  description: ""
  categories:  'Discussion'
  date: "May 10, 2024"
  end_date: "May 10, 2024"
  time: "14:00-16:00"
  location:
    name: "Zoom (online)"
    address: ""
    map_url: ""
  format:
    type: 'Discussion'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host:
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p><span class="dunkelrot"><strong>The slildes can be downloaded <a href="../../members/osim/osim_predatorypublishing_2024.pdf" title="OSIM_PredatoryPublishing_2024">here</a></strong></span></p><p>The relevance and validity of the sciences as well as the reputation of scholars are more and more questioned, at best, or put in disrepute, at worst. Upholding the highest quality standards in scholarly communication is thus of vital importance for scholarship as well as for safeguarding the integrity of the scholarly commons and the scholarly ecosystem. Predatory publishing has gained much prominence in recent years as one new persistent phenomenon that undermines the foundation of scholarly publishing and its principles and standards. On the 10th of May you are invited to a lively discussion and exchange on this matter. Veronika Reinertshofer (UB LMU) Susanne Luger (JKU Linz, Project 'Predatory Publishing', Austrians Transition to Open Access 2) and Clara Ginther (University of Veterinary Medicine, Vienna, Project 'Predatory Publishing', Austrians Transition to Open Access 2) will provide short inputs on quality and scholarly publishing as well as predatory publishing. This is interlaced with opportunities for discussion and exploration. The aim is to initiate an ongoing dialogue on how to address these questionable practices which are ever-evolving and changing.</p><p><strong>Instructors:</strong></p><ul>
<li>
<strong>Susanne Luger</strong> is head of the department License Management and Scholarly Services at University Library of the Johannes Kepler University Linz.</li>
<li>
<strong>Clara Ginter</strong> is Head of the University Library at the University of Veterinary Medicine Vienna. They co-lead the project 'Predatory Publishing', part of Austrian Transition to Open Access 2 (AT2OA2).</li>
<li>
<strong>Veronika Reinertshofer</strong> is employee of the University Library of LMU Munich and works in the associated electronic publishing divisions: publishing services open access.</li>
</ul>
<p><strong>Target audience: </strong>This online workshop is open to all LMU employees and students, including people who are not in the OSIM mailing list. You are welcome to join!</p><p><strong>Logistics:</strong> The online OSIM-meeting will this time take the form of a small workshop with discussion led by our three guests, including two co-leaders of the project 'Predatory Publishing', part of Austrian Transition to Open Access 2.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
