---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: 'Workshop "Navigating the Landscape of Scientific Integrity: Insights into open science, replicability, data sharing and questionable research practices in the field of medicine"'
categories: 'Workshop'

# Event categories
event:
  title: 'Workshop "Navigating the Landscape of Scientific Integrity: Insights into open science, replicability, data sharing and questionable research practices in the field of medicine"'
  description: ""
  categories:  'Workshop'
  date: "November 27, 2024"
  end_date: "November 27, 2024"
  time: "NA"
  location:
    name: "CAS LMU, Seestraße 13, 80802 Munich"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host: 
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p> </p><p><strong>Keynote lectures</strong> by:</p><ul>
<li>Tim Morris (UCL, UK, tentative keywords: estimands, good statistical practice in trials)</li>
<li>Laure Wynants (Leuven, BE, tentative keywords : good practice in prognostic modelling, meta-research)</li>
<li>Balazs Aczel (Budapest, HU, tentative keywords : meta-research, multi-analyst studies)</li>
<li>Leonhard Held (Zürich, CH, replicability, data sharing)</li>
<li>Willi Sauerbrei (Freiburg, tentative keywords: structured reporting, STRATOS)</li>
<li>Sarah Friedrich (Augsburg, tentative keywords: synthetic data/anonymization)</li>
<li>Ulrich Mansmann (LMU, tentative keywords: data sharing)</li>
</ul>
<p>The program is not yet finalized and you are welcome to make <strong>suggestions</strong> by e-mail to <a class="g-link-mail" href="mailto:boulesteix@ibe.med.uni-muenchen.de" title="Send email to: boulesteix@ibe.med.uni-muenchen.de">boulesteix@ibe.med.uni-muenchen.de</a> and <a class="g-link-mail" href="mailto:sabine.hoffmann@stat.uni-muenchen.de" title="Send email to: sabine.hoffmann@stat.uni-muenchen.de">sabine.hoffmann@stat.uni-muenchen.de</a>.</p><p>The workshop is part of the <strong>CAS Research Focus „Medical Data Processing" </strong>(<a href="https://www.cas.lmu.de/en/programs/cas-research-focuses/medical-data-processing/" target="_blank">https://www.cas.lmu.de/en/programs/cas-research-focuses/medical-data-processing/</a>).</p><p>You can already <strong>register</strong> at <a href="http://info@cas.lmu.de" target="_blank">info@cas.lmu.de</a>.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
