---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: '"Software Carpentry - R flavored - Philologicum"'
categories: 'Workshop'

# Event categories
event:
  title: '"Software Carpentry - R flavored - Philologicum"'
  description: ""
  categories:  'Workshop'
  date: "March 24, 2025"
  end_date: "March 24, 2025"
  time: "NA"
  location:
    name: "Philologicum room (Veranstaltungsraum) Ludwigstraße 25, 80539 Munich"
    address: ""
    map_url: ""
  format:
    type: 'Workshop'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""


host: 
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>In this Software Carpentry Workshop you will learn the <strong>Unix Shell, Git and R</strong>.</p><p>This example-driven <strong>two-day workshop</strong> will teach core computing skills that will help you be more productive and effective. We'll alternate short tutorials with hands-on practical exercises. Participants are encouraged to help one another and to apply what they are learning to their own research problems during the workshop.</p><p>See the workshop website for more details: <a href="https://lmu-osc.github.io/2025-03-24-LMU-Humanities/" target="_blank">https://lmu-osc.github.io/2025-03-24-LMU-Humanities/</a></p><p><strong>Instructors:</strong>  Laura Meier, Maximilian Frank, Florian Kohrt</p><p><strong>Helpers</strong>: Pat Callahan, Sarah von Grebmer zu Wolfsthurn</p><p>Registration is mandatory, and participation requires setting up the software in advance by following the provided instructions (a help desk session will take place on March 21st). Please register only if you are available for the whole course.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
