---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: 'Von “DEAL” zu “Diamond”?'
categories: 'Symposium'

# Event categories
event:
  title: 'Von “DEAL” zu “Diamond”?'
  description: ""
  categories:  'Symposium'
  date: "June 24, 2025"
  end_date: "June 24, 2025"
  time: "NA"
  location:
    name: "Hybrid (Ludwigstraße 25, Munich and via Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Symposium'
    detail: ""
  language:
    primary: "German"
    primary-code: "de"
    detail: ""
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""

organizers:
  name: ""

host: 
  - name: "LMU Open Science Center"
---
<!-- MANDAORY SECTION START  -->
<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Seit Abschluss der DEAL-Verträge mit Elsevier, SpringerNature und Wiley sind die Publikationskosten für viele Fachbereiche gestiegen. Für manche ist Publizieren zu einer finanziellen Herausforderung geworden. An vielen Fakultäten wird daher intensiv über den Umgang mit diesen Kosten und über das kommerzielle Publikationssystem im Allgemeinen diskutiert. Das LMU Open Science Center möchte mit dieser Veranstaltung eine Plattform bieten, um drei Aspekte zu beleuchten und zu diskutieren:</p><p><strong>Teil I (16:00–17:00; hybrid) – Nachgefragt: Status Quo von DEAL &amp; Co. und Handhabung der Publikationskosten an der LMU</strong><br>Veronika Reinertshofer von der Universitätsbibliothek erläutert den aktuellen Stand der DEAL-Verträge, räumt typische Missverständnisse aus und beantwortet Ihre Fragen. Außerdem zeigen wir praxisorientiert auf, wie Sie im bestehenden System möglichst offen publizieren – von den OA-Fördermitteln der LMU bis zu „Green Open Access“.</p><p><strong>Teil II (17:00–18:00; hybrid) – Weitergedacht: Modelle jenseits von DEAL und die Rückgewinnung wissenschaftlicher Autonomie</strong><br>Wir zeigen Best-Practice-Beispiele wie gemeinwohlorientierte Infrastrukturen aufgebaut werden können und beleuchten internationale Trends, welche Rolle Fachcommunities und Hochschulen beim Publizieren ohne kommerzielle Verlage spielen könnten. Prof. Markus Gebhardt (LMU) berichtet von der Gründung eines Diamond-OA-Journals an der LMU, Prof. Felix Schönbrodt (LMU) wird die “Peer Community In (PCI)” Plattform vorstellen, welche bereits in vielen Disziplinen eine Qualitätssicherung durch Peer Review nicht-kommerziell organisiert. Prof. Björn Brembs (Universität Regensburg) diskutiert, wie traditionelle Journals gänzlich durch dezentrale und resiliente Infrastrukturen ersetzt werden können, die durch Interoperabilität und offene Standards vernetzt sind.</p><p><strong>Optionaler Teil III (18:00–19:00; nur vor Ort) – Vernetzt vor Ort: Konkrete Schritte für die LMU</strong><br>Vertreterinnen und Vertreter verschiedener Fakultäten tauschen sich über die jeweilige Betroffenheit der einzelnen Disziplinen aus und erörtern etwaige Überlegungen / Strategien auf Instituts-/Fakultätsebene. Sie diskutieren in dem Rundgespräch Handlungsspielräume im aktuellen System, Wünsche an zukünftige Verhandlungsrunden sowie Strategien, um statt symptomorientierter Maßnahmen nachhaltige Systemveränderungen anzustoßen.</p><p>Da die Platzzahl vor Ort limitiert ist, ist eine vorherige Anmeldung notwendig, insbesondere für Personen, die auch an Teil III teilnehmen wollen. Eine Teilnahme an Teil I und II ist online ohne Platzbeschränkung möglich.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
