---
title: "Statute"
format: 
  html:
    grid:
      sidebar-width: 100px
      body-width: 1050px
      margin-width: 200px
    css: 
      - /assets/bootstrap-5.3.8-dist/css/bootstrap.min.css
    toc: false
    page-layout: full
---

<style>
  /* css styles */
:root {
    --primary-color: #00883A;
    --primary-light: rgba(43, 134, 75, 0.1);
    --text-dark: #333333;
    --text-light: #ffffff;
    --osc-white: #ffffff;
    --text-light: #5f5f5f;
    --lmu-black: #232323;
  }
  
#quarto-content.page-columns main.column-page{
    margin:0 auto;
    max-width: 1200px;
    padding: 2rem;
    width:100%;
    /*background-color: #f9fcf9*/
}


.statute-container {
    padding: 2rem;
    display: flex;
    flex-direction: column;
    width: 100%;
    margin-bottom: 1rem;
    background-color:var(--osc-white);
}

.statute-title h3{
    font-size: 2.3rem;
    font-weight: 900;
    line-height: 1.5;
    color:var(--primary-color);
}

h4{
    font-size: 1.1rem;
    line-height: 1.5;
    font-weight: 600; 
    color: #525252;
}

.statute-container p,
.statute-container li {
    text-align: justify;
    font-size: 1rem;
    line-height: 1.85;
    font-weight:400;
    color: var(--text-light);
}
.statute-container p{
    padding: 0 1rem;
}

.osc-stat-note {
    background-color: #00883A10;
    position: relative;
    padding: 0.3rem;
    border: 1px solid #277c4542;
    border-radius: 6px;
    margin-top: 1rem;
    margin-bottom: 1rem;
    width:50%;
}

.osc-stat-note__icon {
    width: 25px;
    height: 25px;
    border-radius: 50%;
    position: absolute;
    top: -16px;
    right: 3px;
    color: #277c45;
    background-color: #47b66d33;
    display: flex;
    align-items: center;
    justify-content: center;
}

.osc-stat-note__icon i {
    font-size: 20px;
}

.osc-stat-note__text {
    margin-top: 0;
    font-size: 0.9rem;
    font-weight: 400;
    color: var(--primary-color);
}


</style>

:::{.statute-container}

:::{.statute-title}
### OSC Statute
:::

```{=html}
<div class="osc-stat-note">
    <div class="osc-stat-note__text">
        <i>
        This statute only exists in German.
        </i>
    </div>
        <div class="osc-stat-note__icon">
        <i class="bi bi-info-circle"></i>
    </div>
</div>
```
#### § 1 Organisationsform und Sitz
 1. Gemäß Beschluss der Hochschulleitung vom 22.11.2017 wird auf Vorschlag der Versammlung der Gründungsmitglieder an der Ludwig-Maximilians-Universität München (LMU) das LMU Open Science Center (OSC) errichtet.
 2. Das OSC ist eine von der LMU getragene, nicht rechtsfähige Arbeitsgemeinschaft von Wissenschaftlerinnen und Wissenschaftlern, insbesondere der LMU. Haushaltstechnisch ist das OSC dem Department Psychologie zugeordnet.
   
#### § 2 Aufgabe
^1^Das OSC fördert im Zusammenwirken seiner interdisziplinären Mitglieder eine transparente und reproduzierbare Wissenschaft („Open Science“) an der LMU und darüber hinaus. ²Open Science beinhaltet unter anderem, Studien wo möglich zu präregistrieren, wissenschaftliche Primärdaten und Material offen bereitzustellen, Berechnungen reproduzierbar zu machen und die Forschungsergebnisse durch Open Access für die Allgemeinheit verfügbar zu machen. ³Unabhängige Replikationsstudien sind darüber hinaus essentiell, um die Robustheit und Generalisierbarkeit von Forschungsergebnissen zu überprüfen. ⁴Diese Praktiken erhöhen die Effizienz, Validität und Glaubwürdigkeit der Forschung. ⁵Das OSC möchte diese Praktiken guter wissenschaftlicher Arbeit u.a. fördern durch

  - Trainingsprogramme und Workshops für Nachwuchswissenschaftlerinnen und Nachwuchswissenschaftler sowie etablierte Forscherinnen und Forscher,
  - öffentliche Vorträge, 
  - die Entwicklung von Kerncurricula,
  - eigene Forschung im Bereich Meta-Science und 
  - die Entwicklung und Implementierung alternativer Anreizstrukturen, welche die Umsetzung von Open Science fördern. 

^6^Darüber hinaus ist es ein Ziel des OSC, in einen (inter-)nationalen Dialog mit Drittmittelgebern, Infrastrukturanbietern, wissenschaftlichen Verlagen und weiteren Interessengruppen zu treten, um auch auf diesem Weg Forschungstransparenz zu fördern.


#### § 3 Mitglieder

1. Das OSC hat ordentliche, außerordentliche, assoziierte und institutionelle Mitglieder:

   1. Ordentliche Mitglieder sind an der LMU tätige Hochschullehrerinnen und Hochschullehrer, die beabsichtigen, im Sinne der Zielsetzungen des OSC nach § 2 Open Science zu fördern.
   2. Außerordentliche Mitglieder sind andere Wissenschaftlerinnen und Wissenschaftler der LMU, die im Sinne der Zielsetzung des § 2 tätig sind, wenn durch die Zusammenarbeit mit ihnen das Erreichen der in § 2 genannten Ziele gefördert wird.
   3.  Assoziierte Mitglieder sind Wissenschaftlerinnen und Wissenschaftler anderer Universitäten und außeruniversitärer Einrichtungen, die im Sinne der Zielsetzung des § 2 tätig sind, wenn durch die Zusammenarbeit mit ihnen das Erreichen der in
   § 2 genannten Ziele gefördert wird.
   4. Institutionelle Mitglieder sind

       - wissenschaftliche Einrichtungen der LMU (z. B. Fakultäten, Departments),
       - zentrale Einrichtungen der LMU sowie
       - außeruniversitäre Einrichtungen, die für die LMU infrastrukturelle Dienstleistungen erbringen,

    die im Sinne der Zielsetzung des § 2 tätig sind, wenn durch die Zusammenarbeit mit ihnen das Erreichen der in § 2 genannten Ziele gefördert wird.

2. ^1^Die Mitgliedschaft wird auf Antrag durch Entscheidung des Vorstandes begründet (§ 6 Abs. 2 Nr. 1). ^2^Die Mitgliedschaft erlischt:

   1. bei Beendigung der wissenschaftlichen Tätigkeit im Sinne von § 2; die Beendigung der wissenschaftlichen Tätigkeit muss dabei durch einen Beschluss des Vorstands festgestellt werden,
   2. bei institutionellen Mitgliedern nach Abs. 1 Nr. 4 c) im Falle des Endes der Zusammenarbeit mit der LMU,
   3. beim Ausscheiden eines Mitglieds auf eigenen Wunsch nach schriftlicher Mitteilung, die an die Sprecherin oder den Sprecher des OSC zu richten ist,
   4. durch Beschluss der Mitgliederversammlung, der in geheimer Abstimmung mit Zweidrittelmehrheit der anwesenden stimmberechtigten Mitglieder gefasst werden muss.

3. Ein ordentliches oder außerordentliches Mitglied, das in einem Beamten- oder Angestelltenverhältnis tätig ist, erfüllt durch seine Mitarbeit im OSC Dienstaufgaben, sofern gesetzliche Bestimmungen sowie die Ausgestaltung des Dienst- und Arbeitsverhältnisses nicht entgegenstehen.

4.  Die Mitglieder des Zentrums sollen nach Möglichkeit Drittmittel und Spenden für OSC-Projekte einwerben. ^2^Alle dem OSC zur Verfügung stehenden Mittel werden von der LMU unter einer eigenen Anordnungsstelle gesondert verwaltet.

#### § 4 Organe

Organe des OSC sind die Mitgliederversammlung (§ 5) und der Vorstand (§ 6).

#### § 5 Mitgliederversammlung

1.  Die Mitgliederversammlung bilden:
    1. die ordentlichen Mitglieder (§ 3 Abs. 1 Nr. 1),
    2. bis zu drei Vertreterinnen und Vertreter der an der LMU beschäftigten außerordentlichen Mitglieder, die vom Vorstand auf Vorschlag der außerordentlichen Mitglieder (§ 3 Abs. 1 Nr. 2) bestellt werden.

2.  Die Mitgliedersammlung hat folgende Aufgaben:
    - Verabschiedung eines Statuts auf Vorschlag des Vorstandes,
    - Beratung über die Tätigkeit des OSC,
    - Entscheidung über die Gestaltung des Lehrprogramms der gemeinsam organisierten Lehrveranstaltungen; die Zuständigkeit der Fakultätsräte bleibt unberührt.
    - Empfehlungen für Themen und Organisation von Vorlesungsreihen, Ferienakademien, Konferenzen, Kolloquien, usw.,
    - Wahl des Vorstands,
    - Entlastung des Vorstands,
    - Entscheidung über die Auflösung des OSC.

3.  ^1^Die Mitgliederversammlung ist von der Sprecherin oder dem Sprecher des Vorstandes mindestens einmal im Jahr einzuberufen. ^2^Die außerordentlichen Mitglieder (§ 3 Abs. 1 Nr. 2) werden zur Mitgliederversammlung eingeladen und wirken bis auf die vom Vorstand bestellten stimmberechtigten außerordentlichen Mitglieder beratend mit. ^3^Die assoziierten Mitglieder können in beratender Funktion an den Mitgliederversammlungen teilnehmen. ⁴Die institutionellen Mitglieder können durch eine Vertreterin oder einen Vertreter repräsentiert werden, welche in beratender Funktion an den Mitgliederversammlungen teilnehmen können. ^5^Auf Wunsch von mindestens einem Drittel der stimmberechtigten Mitglieder ist eine Mitgliederversammlung innerhalb von zwei Wochen einzuberufen. ^6^Die Sprecherin oder der Sprecher führt den Vorsitz. ^7^Beschlüsse erfordern die einfache Mehrheit der anwesenden stimmberechtigten Mitglieder mit Ausnahme der Beschlüsse nach Abs. 2 Nrn. 1 und 7, die der Zweidrittelmehrheit der anwesenden stimmberechtigten Mitglieder bedürfen. 8Stimmrechtsübertragung ist nicht zulässig.

#### § 6 Vorstand

1. ^1^Der Vorstand des OSC besteht aus fünf Mitgliedern,

    1. die überwiegend Professorinnen und Professoren der LMU sein müssen,
    2. zu denen eine Vertreterin oder ein Vertreter der wissenschaftlichen Mitarbeiterinnen und Mitarbeiter gehören soll,
    3. die verschiedene Fachrichtungen vertreten sollen und
    4. die von der Mitgliederversammlung aus dem Kreis ihrer stimmberechtigten Mitglieder (§ 5 Abs. 1) für die Dauer von zwei Jahren gewählt werden.

  ^2^Wiederwahl ist zulässig. ^3^Scheidet ein Mitglied vorzeitig aus dem Vorstand aus, erfolgt für den Rest der Amtszeit eine Nachwahl.

2. Aufgaben des Vorstandes sind:

    - Entscheidung über die Aufnahme neuer ordentlicher, außerordentlicher, assoziierter und institutioneller Mitglieder,
    - Entscheidung über die Vergabe der dem OSC zur Verfügung stehenden Mittel,
    - Förderung der wissenschaftlichen und praktischen Arbeit des OSC mit Rat und Tat,
    - Erstellung eines jährlichen Tätigkeitsberichts des OSC; Berichtsjahr ist das akademische Jahr.

3. ^1^Der Vorstand trifft sich mindestens einmal pro Semester. ^2^Auf Wunsch von mindestens einem Drittel der Mitglieder des Vorstands ist eine Sitzung innerhalb von zwei Wochen einzuberufen.

4. Für den Geschäftsgang gelten § 69 Abs. 1 bis 3, Abs. 4 Satz 1, Abs. 5, Abs. 7 und Abs. 8 der Grundordnung der LMU entsprechend.

#### § 7 Sprecher oder Sprecherin

1. ^1^Der Vorstand wählt aus dem Kreis der ihm angehörenden Professorinnen und Professoren für die Dauer von zwei Jahren eine Sprecherin oder einen Sprecher und eine Stellvertreterin oder einen Stellvertreter. ^2^Wiederwahl ist zulässig. 3Scheidet die Sprecherin oder der Sprecher bzw. die stellvertretende Sprecherin oder der stellvertretende Sprecher vorzeitig aus ihrem bzw. seinem Amt aus, erfolgt für den Rest der Amtszeit eine Nachwahl.

2. Aufgaben der Sprecherin oder des Sprechers sind:

    - Ausführung der Beschlüsse der Mitgliederversammlung und des Vorstandes,
    - Führung der Geschäfte des OSC,
    - Vertretung des OSC nach außen,
    - Einberufung und Leitung der Mitgliederversammlung und der Vorstandssitzungen.

#### § 8 Geschäftsführung

^1^Die Sprecherin oder der Sprecher des OSC kann bei der Erledigung der Aufgaben durch eine wissenschaftliche Geschäftsführerin oder einen wissenschaftlichen Geschäftsführer unterstützt werden. ^2^Die Geschäftsführerin oder der Geschäftsführer wird auf Weisung der Sprecherin oder des Sprechers tätig. ³Falls die Geschäftsführerin oder der Geschäftsführer nicht selbst Vorstandsmitglied ist, nimmt sie oder er ohne Stimmrecht beratend an den Sitzungen des Vorstands teil.

#### § 9 Auflösung

^1^Beschließt die Mitgliederversammlung nach § 5 Abs. 2 Nr. 7 die Auflösung des OSC, fallen die dem OSC zur Verfügung stehenden Mittel nach einem von der Mitgliederversammlung zu beschließenden Schlüssel denjenigen Einrichtungen der LMU zu, an denen die ordentlichen Mitglieder im Sinne von § 3 Abs. 1 Nr. 1 tätig sind. ^2^Die Sprecherin oder der Sprecher informiert die Universitätsleitung umgehend von der beschlossenen Auflösung des OSC.

#### § 10 Schlussvorschriften

1. Dieses Statut wurde von der Versammlung der Gründungsmitglieder am 26.10.2017 beschlossen.
2. Änderungen oder Ergänzungen des Statuts werden mit Genehmigung durch den Präsidenten der LMU wirksam.

:::